[build]
  command = "npm run build"
  publish = "client/dist"  # or "client/build" for Create React App

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200